# Usar a imagem base de Ollama
FROM ollama/ollama:latest

# Instalar curl e limpar a cachê
RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Definir variáveis de ambiente
ENV OLLAMA_KEEP_ALIVE=24h \
    OLLAMA_HOST=0.0.0.0

# Definir o diretório de trabalho
WORKDIR /root/.ollama

# Copiar os arquivos e configurações para o contêiner
COPY . .

# Copiar o script de inicialização e torná-lo executável
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Expor a porta necessária
EXPOSE 11434

# Comando para iniciar o serviço e executar o script
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
